In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
print np.einsum('ij->j', X)

[30 34 38 42 46]


In [9]:
print np.einsum('ij->i', X)

[10 35 60 85]


In [17]:
print np.einsum('ij->ji', X)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [18]:
A = np.arange(3*3*4).reshape((3, 3, 4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [24]:
print np.einsum('ik,jk->ij', X, X)

[[  30   80  130  180]
 [  80  255  430  605]
 [ 130  430  730 1030]
 [ 180  605 1030 1455]]


In [25]:
print np.dot(X, X.T)

[[  30   80  130  180]
 [  80  255  430  605]
 [ 130  430  730 1030]
 [ 180  605 1030 1455]]


In [26]:
print np.einsum('ki,kj->ij', X, X)

[[350 380 410 440 470]
 [380 414 448 482 516]
 [410 448 486 524 562]
 [440 482 524 566 608]
 [470 516 562 608 654]]


In [27]:
print np.dot(X.T, X)

[[350 380 410 440 470]
 [380 414 448 482 516]
 [410 448 486 524 562]
 [440 482 524 566 608]
 [470 516 562 608 654]]


In [31]:
print np.einsum('ik,ik->k', X, X)

[350 414 486 566 654]
